### ISSUE TITLE
Config folder not properly created at first launch

### ISSUE THREAD

**Issue by EtienneAb3d** [PopoutApps/popout3d#1]
Installed from the DEB package.

First launch returns with this error:
```
Cannot find default preferences file.
preferences file failed to load. 
Error in preferences file 
Traceback (most recent call last):
  File "/usr/bin/popout3d", line 1017, in <module>
    main = GUI()	
  File "/usr/bin/popout3d", line 964, in __init__
    getpreferences()
  File "/usr/bin/popout3d", line 224, in getpreferences
    with open(configfold + preffile, 'w') as fn:			
FileNotFoundError: [Errno 2] Aucun fichier ou dossier de ce type: '/home/etienne/.config/popout3d/popout3d.dat'
```
Manually creating a folder` /home/etienne/.config/popout3d` solved the problem.

**Comment by PopoutApps** [comment]
This relates to the Debian package not the Flatpak. Fixed in V1.5.2

**Comment by PopoutApps** [comment]
This relates to the Debian package not the Flatpak. Fixed in Debian V1.5.2
